baseURL: 'https://www.thomas-huehn.com/'
author: Thomas Hühn
languageCode: 'en'
title: 'Readings'

assetDir: 'assets'
dataDir: 'data'

disableHugoGeneratorInject: true
disableKinds:
    - section
    - robotsTXT
    - 404
    - taxonomy
    
permalinks:
  post: '/:contentbasename/'
  page: '/:contentbasename/'

outputFormats:
    RSS:
        mediatype: "application/rss"
        baseName: "feed"

markup:
    goldmark:
        renderer:
            unsafe: true
        parser:
            wrapStandAloneImageWithinParagraph: false
    highlight:
        style: bw
        noClasses: false

params:
    description: "Reading notes and thoughts by Thomas Hühn - Book reviews, technical insights, and personal reflections"
    links:
        - title: "Home"
          url: "/"
        - title: "Thomas Hühn"
          url: "/thomas/"

ignoreFiles:
    - \.jpg$
    - \.png$
    - \.svg$
